version: '3.3'
services:
  php:
    image: luma-php:1.0
    volumes:
      - "./docker/php/php.ini:/usr/local/etc/php/php.ini"
      - ".:/app"

  nginx:
    image: nginx:1.17.0
    ports:
      - "80:80"
    volumes:
      - "./docker/nginx.conf:/etc/nginx/conf.d/default.conf"
      - ".:/app"
    depends_on:
      - "php"

  db:
    image: mariadb:10.4.17-focal
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "mysql-data:/var/lib/mysql"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  elasticsearch:
    image: elasticsearch:6.8.13
    environment:
      - discovery.type=single-node
    volumes:
      - "elasticsearch_data:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"

  redis:
    image: redis:5.0.4

volumes:
  mysql-data:
  elasticsearch_data:
